# Generated by Django 3.1.7 on 2021-03-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='static/<django.db.models.fields.CharField>.png'),
        ),
    ]
